### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by fredfroh** [MakeMagazinDE/Taupunktluefter#9]
Hallo, ein Datenlogging via Netzwerkprotokoll MQTT würde vorziehen.
WLAN ist vorhanden, wie könnte das realisiert werden?

**Comment by koozala** [comment]
Die Software und die Sensoren laufen auch auf einem ESP32 Board. Es gibt ESP32-Module mit integriertem WLAN. MQTT müsste auch verfügbar sein, siehe [hier](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mqtt.html).

**Comment by fredfroh** [comment]
Danke für den Hinweis, das funktioniert :-)
